openapi: 3.0.1
info:
  title: STD21011 Poll project
  description: 'API specification for poll project'
  version: 1.0.0
servers:
 - url: https://localhost:8080.com
tags: 
 - name: Team 
 - name: Match

paths:
  /teams:
    get:
      tags:
        - "Team"
      description: get list of team with players
      responses:
        200:
          description: list of team with players
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /matchs:
    get:
      tags:
        - "Match"
      description: get list of all matchs
      responses:
        200:
          description: list of all matchs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  
  /matchs/{idMatch}:
    get:
      tags:
        - "Match"
      description: get scores details by match id 
      parameters:
        - name: idMatch
          in: path 
          description: id of the match for which you want to see the score
          required: true
          schema: 
            type: number
      responses:
        200:
          description: list of match scores with details
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Match'

components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Player:
      properties:
        id:
          type: integer
        name:
          type: string
        isGuardian:
          type: boolean
    SponsorResponse:
      type: object
      properties:
        id: 
          type: integer
          example: 1
        name:
          type: string
          example: Telma
    PlayedTeam:
      allOf:
        - $ref: '#/components/schemas/Team'
      properties:
        goals:
          type: integer
        scorers:
          type: array
          items:
            $ref: '#/components/schemas/Scorers'
    Match:
      type: object
      properties:
        id:
          type: integer
        datetime:
          type: string
          format: datetime
        stadium:
          type: string
        teamHome:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
        teamAway:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
    Scorers:
      type: object
      properties:
        player:
          $ref: '#/components/schemas/Player'
        isOG:
          type: boolean
        scoreTime:
          type: integer